EyeQuiz.Managment/Models/ErrorViewModel.cs
using System;

namespace EyeQuiz.Managment.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EyeQuiz.Managment/Models/QuestionVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EyeQuiz.Managment.Models
{
    public class QuestionVM
    {
        
        public string QuestionName { get; set; }
        public string AnswerA { get; set; }
        public string AnswerB { get; set; }
        public string AnswerC { get; set; }
        public string AnswerD { get; set; }
        public int Point { get; set; }
        public string CorrectVariant { get; set; }

    }
}

EyeQuiz.Managment/Controllers/EventsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EyeQuiz.Managment.Controllers
{
    public class EventsController : Controller
    {
        public EventsController()
        {
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

EyeQuiz.Managment/Controllers/ExamController.cs
using EyeQuiz.Managment.Entites;
using EyeQuiz.Managment.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace EyeQuiz.Managment.Controllers
{
    public class ExamController : Controller
    {
        private readonly DataContext context;

        public ExamController(DataContext context)
        {
            this.context = context;
        }
        [HttpGet]
        public IActionResult Test(int? result)
        {
            var questions = context.Questions.ToList();
            ViewBag.Result = result;
            return View(questions);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View(new QuestionVM());
        }

        [HttpPost]
        public IActionResult Create(QuestionVM vm)
        {
            if (ModelState.IsValid)
            {
                Question q = new Question
                {
                    QuestionName = vm.QuestionName,
                    AnswerA = vm.AnswerA,
                    AnswerB = vm.AnswerB,
                    AnswerD = vm.AnswerD,
                    AsnwerC = vm.AnswerC,
                    CorrectAnswer = vm.CorrectVariant,
                    Point=vm.Point
                };
                context.Questions.Add(q);
                
                var isSave = context.SaveChanges();
                if (isSave > 0)
                {
                    return RedirectToAction("Index", "Home");
                }
                throw new Exception("Database ex");

            }

            return View();
        }
        [HttpPost]
        public ActionResult SetAnswer(List<string> answer)
        {

            var questions = context.Questions.ToList();

            int sum = 0;
            foreach (var question in questions)
            {
                foreach (string yourAnswer in answer)
                {
                    if (ValidateCorrectVariant(question.CorrectAnswer, yourAnswer))
                    {
                        sum = sum + question.Point;
                        break;
                    }
                }
            }

            if (sum < 30)
            {
                TempData["Valid"] = "Siz Kesilmisiniz ";
            }
            else if (sum > 100)
            {
                TempData["Valid"] = "Elasan";
            }

                    
            return RedirectToAction("Test", new { result = sum });
        }

        private bool ValidateCorrectVariant(string correct, string yourAnswer)
        {
            return (correct == yourAnswer);
        }
    }
}

EyeQuiz.Managment/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EyeQuiz.Managment.Models;

namespace EyeQuiz.Managment.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EyeQuiz.Managment/Views/Events/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

EyeQuiz.Managment/Views/Exam/Create.cshtml
@model QuestionVM
@{
    ViewData["Title"] = "Create";
}

<div class="container">
    <div class="row">
        <div class="col-5">

            <form asp-action="Create" asp-controller="Exam" method="post">
                <div class="form-group">
                    <label asp-for="QuestionName">Question</label>
                    <textarea class="form-control" asp-for="QuestionName" rows="3"></textarea>
                </div>

                <div class="form-group">
                    <label asp-for="AnswerA">Variants</label>
                    <input asp-for="AnswerA" class="form-control form-control-lg" type="text" placeholder="A variant">
                </div>
                <div class="form-group">
                    <label asp-for="AnswerB">Variants</label>
                    <input asp-for="AnswerB" class="form-control form-control-lg" type="text" placeholder="B variant">
                </div>
                <div class="form-group">
                    <label asp-for="AnswerC">Variants</label>
                    <input asp-for="AnswerC" class="form-control form-control-lg" type="text" placeholder="C variant">
                </div>
                <div class="form-group">
                    <label asp-for="AnswerD">Variants</label>
                    <input asp-for="AnswerD" class="form-control form-control-lg" type="text" placeholder="D variant">
                </div>
                <div class="form-group">
                    <label asp-for="Point">Point</label>
                    <input asp-for="Point" class="form-control form-control-lg" type="number" placeholder="Point">
                </div>
                <div class="form-group">
                    <label asp-for="CorrectVariant">Correct</label>
                    <input asp-for="CorrectVariant" class="form-control form-control-lg" type="text" placeholder="Correct Variant">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success">Create Question</button>
                </div>

            </form>
        </div>
    </div>
</div>

EyeQuiz.Managment/Views/Exam/Test.cshtml
@model IEnumerable<EyeQuiz.Managment.Entites.Question>
@{
    ViewData["Title"] = "Test";
}

<form asp-action="SetAnswer" asp-controller="Exam" id="mineForm" method="post">
    @{
        int i = 0;
        int count = 1;
    }
    @foreach (var question in Model)
    {

        <div>
            <div class="alert alert-dark mt-5" role="alert">
                @count . @question.QuestionName
            </div>
            <div class="form-check">
                <input class="form-check-input" group type="radio" name="answer[@i]"  value="@(question.AnswerA!=null ? question.AnswerA : null)">
                <label class="form-check-label" for="answer">
                      @question.AnswerA
                </label>
            </div>

            <div class="form-check">
                <input class="form-check-input" type="radio" name="answer[@i]"  value="@(question.AnswerB!=null ? question.AnswerB : null)">
                <label class="form-check-label" for="answer">
                     @question.AnswerB
                </label>
            </div>


            <div class="form-check">
                <input class="form-check-input" type="radio" name="answer[@i]" value="@(question.AsnwerC!=null ? question.AsnwerC : null)">
                <label class="form-check-label" for="answer">
                     @question.AsnwerC
                </label>
            </div>

            <div class="form-check">
                <input class="form-check-input" type="radio" name="answer[@i]" value="@(question.AnswerD!=null ? question.AnswerD : null)">
                <label class="form-check-label" for="answer">
                     @question.AnswerD
                </label>
            </div>
            <input type="hidden" name="answer[@i]" value="@null" />
        </div>



        i++;
        count++;

        
    }
    <button type="submit" class="btn btn-primary">Calculate Result!!!</button>
    <h1>Score:@ViewBag.Result  Message: @TempData["Valid"]</h1>
</form>

EyeQuiz.Managment/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EyeQuiz.Managment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EyeQuiz.Managment</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EyeQuiz.Managment</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - EyeQuiz.Managment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)

    <script>

        setTimeout(function () {

            $(function () {
                console.log('fake');
                $('#mineForm').submit(function (e) {
                    console.log('take it');


                });
            });
        }, 1500);
    </script>
</body>
</html>